---
# tasks file for ec2_instance

- name: Launch ec2 instance
  ec2:
          aws_access_key: "{{ access_key }}"
          aws_secret_key: "{{ secret_key }}"
          key_name: keyt
          instance_type: t2.micro
          image: ami-0ebc1ac48dfd14136
          wait: yes
          instance_tags:
                  name: webserver
          group_id: "sg-09f8fc848cf88fe67"
          count: 1
          vpc_subnet_id: subnet-bdc3f3d5
          assign_public_ip: yes
          region: ap-south-1
  register: ec2details
